[package]
name = "scylla-migrate"
version = "0.1.1"
edition = "2021"
description = "A migration tool for ScyllaDB"
license = "MIT"
repository = "https://github.com/jimmielovell/scylla-migrate"

[[bin]]
name = "scylla-migrate"
path = "src/bin/main.rs"

[lib]
name = "scylla_migrate"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
scylla = { version = "1.1.0", features = ["time-03", "num-bigint-03"]}
sha2 = "0.11.0-pre.4"
time = { version = "0.3.41", features = ["formatting"] }
tokio = { version = "1.44.2", features = ["fs", "macros", "rt-multi-thread"] }

[dev-dependencies]
tempfile = "3.20.0"
